[package]
name = "ziggurat-algorand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fs_extra = "1.2"
home = "0.5.3"
tempfile = "3.3"
toml = "0.5.9"

[dependencies.serde]
version = "1"
features = [ "derive" ]

[dependencies.tokio]
version = "1"
features = [ "full" ]
